name: flutter_sphinx
description: a plugin that adds pocketsphinx speech recognition to a flutter app
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  audioplayers: ^0.20.1
  flutter:
    sdk: flutter
  flutter_tts: ^3.3.3
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.flutter_sphinx
        pluginClass: FlutterSphinxPlugin
      ios:
        pluginClass: FlutterSphinxPlugin

    # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/flutter_sphinx/sync/assets.lst
    - packages/flutter_sphinx/sync/cmudict-en-us.dict
    - packages/flutter_sphinx/sync/digits.gram
    - packages/flutter_sphinx/sync/en-phone.dmp
    - packages/flutter_sphinx/sync/en-us-ptm/feat.params
    - packages/flutter_sphinx/sync/en-us-ptm/mdef
    - packages/flutter_sphinx/sync/en-us-ptm/means
    - packages/flutter_sphinx/sync/en-us-ptm/noisedict
    - packages/flutter_sphinx/sync/en-us-ptm/sendump
    - packages/flutter_sphinx/sync/en-us-ptm/transition_matrices
    - packages/flutter_sphinx/sync/en-us-ptm/variances
    - packages/flutter_sphinx/sync/menu.gram
    - packages/flutter_sphinx/sync/weather.dmp
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
